name: eventsource
description: A client and server implementation of Server-Sent Events.
version: 0.4.0
homepage: https://github.com/stevenroose/dart-eventsource

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  collection: ^1.15.0
  http: ^1.1.0
  http_parser: ^4.0.2
  logging: ^1.0.1
  sync: ^0.3.0

dev_dependencies:
  test: ^1.17.11
